import React from "react";
import MarkDown from "react-markdown";
import remarkGfm from "remark-gfm"; // Plugin for GitHub Flavored Markdown (tables, task lists, strikethrough)
import CodeHighlighter from "./_notes/code-highlighter"; // Custom component for code block rendering
import remarkMath from "remark-math"; // Plugin for parsing math (LaTeX)
import rehypeKatex from "rehype-katex"; // Plugin for rendering math (KaTeX)
import "katex/dist/katex.min.css"; // Import KaTeX styles for proper math rendering

/**
 * MarkdownRenderer Component
 * Renders markdown content with custom components for styling and functionality.
 * It uses 'react-markdown' along with remark and rehype plugins for extended features
 * like GitHub Flavored Markdown, math rendering, and custom element styling.
 *
 * @param {object} props - Component props.
 * @param {string} props.content - The markdown string to be rendered.
 * @param {string} [props.className] - Optional Tailwind CSS classes to apply to the main container.
 */
const MarkdownRenderer = ({ content, className }) => {
  return (
    // Main container for the markdown output.
    // Provides a flex column layout with consistent gap between markdown elements.
    <div className={`flex flex-col gap-4 ${className}`}>
      <MarkDown
        // remarkPlugins process the markdown AST (Abstract Syntax Tree) before conversion to HTML.
        // - remarkGfm: Enables GitHub Flavored Markdown features (e.g., tables, task lists, strikethrough).
        // - remarkMath: Parses LaTeX math syntax into a format suitable for rendering.
        remarkPlugins={[remarkGfm, remarkMath]}
        // rehypePlugins process the HTML AST generated by remark-markdown.
        // - rehypeKatex: Renders the math nodes parsed by remarkMath into visually appealing KaTeX.
        rehypePlugins={[rehypeKatex]}
        // 'components' prop allows overriding default HTML elements with custom React components,
        // giving fine-grained control over markdown rendering and styling.
        components={{
          /**
           * Custom component for rendering code blocks.
           * It delegates the actual syntax highlighting and "copy to clipboard" functionality
           * to the `CodeHighlighter` component.
           *
           * @param {object} props - Props passed by react-markdown for a code element (e.g., node, inline, className, children).
           */
          code: ({ node, inline, className, children, ...props }) => {
            // Pass all relevant props to the custom CodeHighlighter.
            return (
              <CodeHighlighter
                node={node}
                inline={inline}
                className={className}
                {...props}
              >
                {children}
              </CodeHighlighter>
            );
          },
          /**
           * Custom component for rendering links (`<a>` tags).
           * Applies Tailwind CSS classes for consistent gray link color, underline, and hover effects.
           *
           * @param {object} props - Props passed by react-markdown for an anchor element.
           */
          a: ({ node, ...props }) => (
            <a
              className="text-gray-600 hover:text-gray-800 underline transition-colors duration-200"
              {...props}
            />
          ),
          /**
           * Custom component for rendering paragraphs (`<p>` tags).
           * Includes special styling logic: if a paragraph starts with '#', it's styled as a "tag".
           *
           * @param {object} props - Props passed by react-markdown for a paragraph element.
           */
          p: ({ node, ...props }) => {
            // Check the first child's text content to determine if it starts with '#'.
            // This is used for a custom "tag" like appearance.
            const firstChildText = Array.isArray(props.children)
              ? props.children[0]?.toString().trim()
              : props.children?.toString().trim();
            const startsWithHash =
              firstChildText && firstChildText.startsWith("#");

            return (
              <p
                className={`${
                  startsWithHash
                    ? "font-bold bg-gray-100  w-fit p-1 rounded-sm text-gray-700  text-sm" // Styling for tag-like paragraphs
                    : ""
                }`}
                {...props}
              />
            );
          },
          /**
           * Custom component for unordered lists (`<ul>` tags).
           * Applies Tailwind CSS for bullet points, left padding, and space between list items.
           * `marker:text-gray-500` styles the bullet itself.
           *
           * @param {object} props - Props passed by react-markdown for a ul element.
           */
          ul: ({ node, ...props }) => (
            <ul
              className="list-disc pl-6 space-y-2 marker:text-gray-500"
              {...props}
            />
          ),
          /**
           * Custom component for ordered lists (`<ol>` tags).
           * Applies Tailwind CSS for decimal numbering, left padding, and space between list items.
           * `marker:text-gray-500` styles the number itself.
           *
           * @param {object} props - Props passed by react-markdown for an ol element.
           */
          ol: ({ node, ...props }) => (
            <ol
              className="list-decimal pl-6 space-y-2 marker:text-gray-500"
              {...props}
            />
          ),
          /**
           * Custom component for input elements, specifically targeting task list checkboxes.
           * Styles checkboxes to match a modern UI and makes them disabled (read-only)
           * as task lists in markdown are typically for display, not interactive input.
           *
           * @param {object} props - Props passed by react-markdown for an input element.
           */
          input: ({ node, ...props }) => {
            if (props.type === "checkbox") {
              return (
                <input
                  type="checkbox"
                  className="form-checkbox h-4 w-4 text-gray-600 rounded border-gray-300 focus:ring-gray-500 cursor-pointer"
                  disabled={true} // Checkboxes in markdown are generally non-interactive
                  {...props}
                />
              );
            }
            return <input {...props} />;
          },
          /**
           * Custom components for various heading levels (h1-h6).
           * Applies bold font, increasing font sizes, bottom borders (for h1, h2),
           * and distinct text colors for visual hierarchy and readability.
           * Includes dark mode support for text colors.
           *
           * @param {object} props - Props passed by react-markdown for a heading element.
           */
          h1: ({ node, ...props }) => (
            <h1
              className="text-3xl md:text-4xl font-extrabold border-b border-gray-200 pb-2 mb-4 mt-6 text-gray-900 "
              {...props}
            />
          ),
          h2: ({ node, ...props }) => (
            <h2
              className="text-2xl md:text-3xl font-bold border-b border-gray-200 pb-1 mb-3 mt-5 text-gray-800 "
              {...props}
            />
          ),
          h3: ({ node, ...props }) => (
            <h3
              className="text-xl md:text-2xl font-semibold mb-2 mt-4 text-gray-700 "
              {...props}
            />
          ),
          h4: ({ node, ...props }) => (
            <h4
              className="text-lg md:text-xl font-semibold mb-1 mt-3 text-gray-700 "
              {...props}
            />
          ),
          h5: ({ node, ...props }) => (
            <h5
              className="text-base md:text-lg font-semibold mt-2 text-gray-600 "
              {...props}
            />
          ),
          h6: ({ node, ...props }) => (
            <h6
              className="text-sm md:text-base font-semibold mt-1 text-gray-500 "
              {...props}
            />
          ),
          /**
           * Custom component for tables.
           * Wraps the table in an `overflow-x-auto` div to ensure horizontal scrolling
           * on small screens. Applies basic table styling for borders and rounding.
           *
           * @param {object} props - Props passed by react-markdown for a table element.
           */
          table: ({ node, ...props }) => (
            <div className="overflow-x-auto my-4 rounded-sm border border-gray-200 ">
              <table
                className="min-w-full divide-y divide-gray-200 "
                {...props}
              />
            </div>
          ),
          /**
           * Custom component for table head (`<thead>` tags).
           * Applies a subtle background color for the table header row.
           *
           * @param {object} props - Props passed by react-markdown for a thead element.
           */
          thead: ({ node, ...props }) => (
            <thead className="bg-gray-50 " {...props} />
          ),
          /**
           * Custom component for table headers (`<th>` tags).
           * Applies padding, text alignment, font styling, and bottom border for table headers.
           *
           * @param {object} props - Props passed by react-markdown for a th element.
           */
          th: ({ node, ...props }) => (
            <th
              className="px-6 py-3 text-left text-xs font-medium text-gray-500  uppercase tracking-wider border-b border-gray-200 "
              {...props}
            />
          ),
          /**
           * Custom component for table data cells (`<td>` tags).
           * Applies padding, ensures content stays on one line (`whitespace-nowrap`),
           * and sets text color and bottom border for table data cells.
           *
           * @param {object} props - Props passed by react-markdown for a td element.
           */
          td: ({ node, ...props }) => (
            <td
              className="px-6 py-4 whitespace-nowrap text-sm text-gray-700  border-b border-gray-200 "
              {...props}
            />
          ),
          /**
           * Custom component for blockquotes (`<blockquote>` tags).
           * Applies a distinct left border, padding, italic text, and a subtle background
           * to visually set blockquotes apart from regular text.
           *
           * @param {object} props - Props passed by react-markdown for a blockquote element.
           */
          blockquote: ({ node, ...props }) => (
            <blockquote
              className="border-l-4 border-gray-400 pl-4 py-1 italic text-gray-700  bg-gray-50/50 /20 rounded-r-md"
              {...props}
            />
          ),
          /**
           * Custom component for images (`<img>` tags).
           * Ensures images are responsive (`max-w-full h-auto`), centered,
           * and have rounded corners and a shadow for a polished look.
           *
           * @param {object} props - Props passed by react-markdown for an image element.
           */
          img: ({ node, ...props }) => (
            <img
              {...props}
              className="max-w-full h-auto rounded-sm shadow-sm my-4 mx-auto block"
            />
          ),
          /**
           * Custom component for horizontal rules (`<hr>` tags).
           * Renders a styled separator line to break up content sections.
           *
           * @param {object} props - Props passed by react-markdown for an hr element.
           */
          hr: ({ node, ...props }) => (
            <hr className="my-8 border-t-2 border-gray-200 " {...props} />
          ),
        }}
      >
        {/* The markdown content to be rendered */}
        {content}
      </MarkDown>
    </div>
  );
};

export default MarkdownRenderer;

// Markdown rederer with mermaid support
// import React, { useLayoutEffect, useRef } from "react";
// import MarkDown from "react-markdown";
// import remarkGfm from "remark-gfm";
// import remarkMath from "remark-math";
// import rehypeKatex from "rehype-katex";
// import mermaid from "mermaid";
// import CodeHighlighter from "./_notes/code-highlighter";
// import "katex/dist/katex.min.css";

// mermaid.initialize({
//   startOnLoad: false,
//   theme: "default",
//   securityLevel: "loose",
// });

// const MermaidBlock = ({ chart }) => {
//   const containerRef = useRef(null);
//   const uniqueId = useRef(`mermaid-${Math.random().toString(36).slice(2, 9)}`);

//   useLayoutEffect(() => {
//     if (!chart || !containerRef.current) return;

//     let isMounted = true;
//     const renderMermaid = async () => {
//       try {
//         const { svg, bindFunctions } = await mermaid.render(
//           uniqueId.current,
//           chart
//         );
//         if (isMounted && containerRef.current) {
//           containerRef.current.innerHTML = svg;
//           bindFunctions?.(containerRef.current);
//         }
//       } catch (err) {
//         if (isMounted && containerRef.current) {
//           console.error("Mermaid render failed:", err);
//           containerRef.current.innerHTML = `<pre class="text-red-500">Error rendering Mermaid diagram:\n${err.message}</pre>`;
//         }
//       }
//     };

//     renderMermaid();
//     return () => {
//       isMounted = false;
//     };
//   }, [chart]);

//   return <div ref={containerRef} className="w-full overflow-auto" />;
// };

// const MarkdownRenderer = ({ content, className }) => {
//   return (
//     <div className={`flex flex-col gap-4 ${className || ""}`}>
//       <MarkDown
//         remarkPlugins={[remarkGfm, remarkMath]}
//         rehypePlugins={[rehypeKatex]}
//         components={{
//           code: ({ node, inline, className = "", children, ...props }) => {
//             const match = /language-(\w+)/.exec(className || "");
//             const lang = match?.[1] || "";

//             if (!inline && lang === "mermaid") {
//               return <MermaidBlock chart={String(children).trim()} />;
//             }

//             return <CodeHighlighter {...props} value={String(children)} />;
//           },
//           a: ({ node, ...props }) => (
//             <a className="text-gray-500 underline" {...props} />
//           ),
//           p: ({ node, ...props }) => {
//             const firstChar = props.children?.[0]
//               ?.toString()
//               ?.trim()
//               ?.charAt(0);
//             const highlightClass =
//               firstChar === "#"
//                 ? "font-bold bg-gray-200 w-fit p-1 rounded text-gray-700"
//                 : "";
//             return <p className={highlightClass} {...props} />;
//           },
//           ul: ({ node, ...props }) => (
//             <ul className="list-disc pl-5 space-y-2" {...props} />
//           ),
//           ol: ({ node, ...props }) => (
//             <ol className="list-decimal pl-5 space-y-2" {...props} />
//           ),
//           input: ({ node, ...props }) => {
//             if (props.type === "checkbox") {
//               return (
//                 <input
//                   type="checkbox"
//                   className="cursor-pointer rounded focus:ring-0"
//                   {...props}
//                 />
//               );
//             }
//             return <input {...props} />;
//           },
//           h1: (props) => <h1 className="text-3xl font-bold" {...props} />,
//           h2: (props) => <h2 className="text-2xl font-bold" {...props} />,
//           h3: (props) => <h3 className="text-xl font-bold" {...props} />,
//           h4: (props) => <h4 className="text-lg font-bold" {...props} />,
//           h5: (props) => <h5 className="text-md font-bold" {...props} />,
//           h6: (props) => <h6 className="text-sm font-bold" {...props} />,
//           table: (props) => (
//             <table
//               className="table-auto border-collapse overflow-auto"
//               {...props}
//             />
//           ),
//           th: (props) => (
//             <th className="border px-4 py-2 bg-gray-200" {...props} />
//           ),
//           td: (props) => <td className="border px-4 py-2" {...props} />,
//           blockquote: (props) => (
//             <blockquote
//               className="border-l-4 border-gray-300 pl-4 italic text-gray-600"
//               {...props}
//             />
//           ),
//           img: (props) => (
//             <img {...props} className="max-w-full rounded-sm mx-auto p-2" />
//           ),
//         }}
//       >
//         {content}
//       </MarkDown>
//     </div>
//   );
// };

// export default MarkdownRenderer;
